#!/usr/bin/env bash
set -x

qemu-system-x86_64 \
  -enable-kvm \
  -serial stdio \
  -soundhw hda \
  -hda ubuntu-desktop/ubuntu-16-04.img \
  -net user,hostfwd=tcp::2222-:22 \
  -net nic \
  -m 4G \
  -smp 4 \
  -cpu host,-rdtscp \
  
